name: Generador de Videos Automatizado

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  construir-y-ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Crear entorno virtual, instalar dependencias y ejecutar script
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python src/profesor.py
